### ISSUE TITLE
Support nested variable transformation

### ISSUE THREAD

**Issue by felixhaeberle** [lukasoppermann/design-token-transformer#8]
First and foremost, thanks for building this great tool!

I recognized that with the the exported text and effect styles as objects, the css variable generation is kinda broken or doesn't resolve properly wit nested key-value pairs because the nested properties aren't recognized and transformed to it's own value.

For example:

```css
--font-headline-2x-large: [object Object];
--font-headline-x-large: [object Object];
--font-headline-large: [object Object];
--font-headline-medium: [object Object];
--font-headline-small: [object Object];
--font-headline-x-small: [object Object];
--font-copy-large: [object Object];
--font-copy-medium: [object Object];
--font-copy-x-small: [object Object];
--font-copy-small: [object Object];
--font-label-medium: [object Object];
--font-label-small: [object Object];
--font-button-medium: [object Object];
--font-button-small: [object Object];
--effect-focus-inner-default-0: [object Object];
--effect-focus-inner-default-1: [object Object];
--effect-focus-outside-default-0: [object Object];
--effect-focus-outside-default-1: [object Object];
--effect-focus-outside-input: [object Object];
--effect-shadow-bottom-400: [object Object];
--effect-shadow-bottom-800: [object Object];
--effect-shadow-right-400: [object Object];
```

The solution:
Having the text style for example `--font-headline-2x-large` as prefix and add the nested property `fontSize` as `font-size` or something similar to generate also the nested key value pairs as variables as `--font-headline-2x-large-font-size`. Same would work for the other generated tokens such as `less` and `scss`. 

What do you think bout this improvement? Is this possible to implement as the standard configuration? 
Thanks for your effort! :)

**Comment by lukasoppermann** [comment]
Hey,

this is the original behavior, however it makes it nearly impossible to prepare the tokens for android and ios and also does not allow for combined styles, e.g. `font` in css.

If you want the old behavior just change the **Token Format** to **Original** in the general settings. https://github.com/lukasoppermann/design-tokens#token-format

Otherwise please have a look at the example conversion which can create a much better output together with the "Standard" format: https://github.com/lukasoppermann/design-tokens/tree/main/examples

Hope that helps, otherwise please comment again.

**Comment by felixhaeberle** [comment]
Thanks for the clarification! I somehow missed to read it out of the documentation in that way. Have a nice day!:)

**Comment by dzena** [comment]
@lukasoppermann 
Amazing plugin.
Is there a plan to add support for nested values? Or we should fallback to writing custom formatters?
Thank you for maintaining all this libs.
